version: '3.8'

services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  person-service:
    build: ./person-service
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  auth-service:
    build: ./auth-service
    depends_on:
      - discovery-server
      - person-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - JWT_SECRET=41Dk432fD23423aADF342lkj234ADF987asdf987ADF345lkj345ADF345ADF345ADF

  account-service:
    build: ./account-service
    depends_on:
      - discovery-server
      - person-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  transaction-service:
    build: ./transaction-service
    depends_on:
      - discovery-server
      - account-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - auth-service
      - person-service
      - account-service
      - transaction-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      # This needs to match the secret in auth-service and gateway's application.yml
      - JWT_SECRET=41Dk432fD23423aADF342lkj234ADF987asdf987ADF345lkj345ADF345ADF345ADF
